name: ilya_savintsev

on:
  push:
    branches: [ "ilya/savintsev/7" ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Установка Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      # 3. Кэш для модулей
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      # 4. Установка зависимостей
      - name: Install dependencies
        run: go mod download

      # 5. Установка golangci-lint
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      # 6. Запуск линтера
      - name: Run golangci-lint
        run: golangci-lint run ./...

      # 7. Запуск тестов с покрытием
      - name: Run tests
        run: go test ./... -cover
